version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "appdirs"
      - match:
          dependency_name: "aspy.yaml"
      - match:
          dependency_name: "astroid"
      - match:
          dependency_name: "attrs"
      - match:
          dependency_name: "cfgv"
      - match:
          dependency_name: "distlib"
      - match:
          dependency_name: "filelock"
      - match:
          dependency_name: "identify"
      - match:
          dependency_name: "importlib-metadata"
      - match:
          dependency_name: "lazy-object-proxy"
      - match:
          dependency_name: "mccabe"
      - match:
          dependency_name: "nodeenv"
      - match:
          dependency_name: "pathspec"
      - match:
          dependency_name: "toml"
      - match:
          dependency_name: "typed-ast"
      - match:
          dependency_name: "virtualenv"
      - match:
          dependency_name: "zipp"
